version: '3.3'

services:
  web:
    build: ./my_api
    command: gunicorn my_resume_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./my_api/:/usr/src/my_api/
    ports:
      - 8001:8000
    env_file:
      - ./prod.env