version: '3.8'

services:
  web:
    build: ./my_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./my_api/:/usr/src/my_api/
    ports:
      - 8000:8000
    env_file:
      - ./dev.env
